# Generated by Django 3.1.6 on 2021-03-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='draft',
        ),
    ]
